"""cascade delete on description_hints category_id

Revision ID: 170285b8d3e7
Revises: 9d112b71cb33
Create Date: 2026-08-07 21:35:01.621648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170285b8d3e7'
down_revision: Union[str, Sequence[str], None] = '9d112b71cb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('description_hints_category_id_fkey'), 'description_hints', type_='foreignkey')
    op.create_foreign_key(None, 'description_hints', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'description_hints', type_='foreignkey')
    op.create_foreign_key(op.f('description_hints_category_id_fkey'), 'description_hints', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
