"""add is_credit to accounts and installment fields to transactions

Revision ID: aae826fba993
Revises: d0712db51641
Create Date: 2026-05-25 23:10:43.013247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae826fba993'
down_revision: Union[str, Sequence[str], None] = 'd0712db51641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_credit', sa.Boolean(),
                  nullable=False, server_default='false'))
    op.add_column('transactions', sa.Column(
        'installment_group_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column(
        'installment_number', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column(
        'installment_total', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column(
        'is_paid', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_paid')
    op.drop_column('transactions', 'installment_total')
    op.drop_column('transactions', 'installment_number')
    op.drop_column('transactions', 'installment_group_id')
    op.drop_column('accounts', 'is_credit')
    # ### end Alembic commands ###
