"""add transfer_direction to transactions

Revision ID: e842ad525b9e
Revises: 27f926e03339
Create Date: 2026-05-20 17:21:11.121042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e842ad525b9e'
down_revision: Union[str, Sequence[str], None] = '27f926e03339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_direction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transfer_direction')
    # ### end Alembic commands ###
